spring.application.name=pelisduoc
server.port=8081

# Oracle Autonomous Database (Wallet)
# Ajusta el path si cambias de carpeta/proyecto.
spring.datasource.url=jdbc:oracle:thin:@r3otlzvdm9gnlibe_high?TNS_ADMIN=C:/oracle/wallet/R3OTLZVDM9GNLIBE
spring.datasource.username=${DB_USERNAME:ADMIN}
spring.datasource.password=Ingreso2025@2025
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Swagger UI (documentacion)
springdoc.swagger-ui.path=/swagger-ui.html

# Tiempo de espera razonable para conexiones remotas
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.validation-timeout=5000
